obj-$(CONFIG_OPLUS_FINGERPRINT_COMMON) += oplus_fp_common/

### Optical fingerprint sensor
obj-$(CONFIG_OPLUS_FINGERPRINT_GOODIX_OPTICAL) += goodix_optical_fp/
obj-$(CONFIG_OPLUS_FINGERPRINT_JIIOV_OPTICAL)   += anc_driver/
