#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHPANEL_GOODIX_GT9886) += GT9886/

oplus_bsp_tp_goodix_comnon-y += gtx8_tools.o  goodix_common.o
obj-$(CONFIG_TOUCHPANEL_GOODIX) += oplus_bsp_tp_goodix_comnon.o
#endif

#endif
